version: '3.5'
services:
  haruka-nats:
    image: nats
    ports:
      - '8222:8222'
      - '4222:4222'
    hostname: nats-server
    networks:
      - nats

  ###: USER
  user-db:
    image: 'mongo'
    container_name: 'user-mongo-db'
    environment:
      - MONGO_INITDB_DATABASE=user
    ports:
      - '27017-27019:27017-27019'
    networks:
      - user
  user-api-nats:
    build:
      context: user
      dockerfile: nats.Dockerfile
    container_name: 'user-nats-api'
    environment:
      - MONGO_URL=mongodb://user-db:27017
      - NATS_URI=http://haruka-nats:4222
      - PORT=5501
    ports:
      - '5501:5501'
    depends_on:
      - user-db
      - haruka-nats
    networks:
      - user
      - nats

  ### AUTH
  auth-db:
    image: 'mongo'
    container_name: 'auth-mongo-db'
    environment:
      - MONGO_INITDB_DATABASE=auth
    ports:
      - '27027-27029:27017-27019'
    networks:
      - auth
  auth-redis:
    image: 'redis'
    container_name: 'auth-redis-db'
    ports:
      - '6379:6379'
    networks:
      - auth
  auth-api-nats:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: 'auth-nats-api'
    environment:
      - MONGO_URL=mongodb://auth-db:27017
      - REDIS_URL=redis://auth-redis:6379
      - NATS_URI=http://haruka-nats:4222
      - PORT=5503
    ports:
      - '5503:5503'
    depends_on:
      - auth-redis
      - auth-db
      - haruka-nats
    networks:
      - auth
      - nats

  ### POST
  post-db:
    image: 'mongo'
    container_name: 'post-mongo-db'
    environment:
      - MONGO_INITDB_DATABASE=post
    ports:
      - '27037-27039:27017-27019'
    networks:
      - post
  post-api-nats:
    build:
      context: post
      dockerfile: command.Dockerfile
    container_name: 'post-command-api'
    environment:
      - MONGO_URL=mongodb://post-db:27017
      - NATS_URI=http://haruka-nats:4222
      - PORT=5504
    ports:
      - '5504:5504'
    depends_on:
      - post-db
      - haruka-nats
    networks:
      - post
      - nats

  ### GATEWAY
  haruka-gateway:
    build:
      context: gateway
      dockerfile: Dockerfile
    container_name: 'haruka-gateway'
    environment:
      - NATS_URL=http://haruka-nats:4222
      - PORT=5502
    ports:
      - '5502:5502'
    depends_on:
      - haruka-nats
      - user-api-nats
      - auth-api-nats
    networks:
      - frontend
      - nats
networks:
  frontend:
  nats:
  user:
    name: user-network
  auth:
    name: auth-network
  post:
    name: post-network
